const DummyWidgets = [
  {
    id: 1,
    name: "Hero Section",
    title: "Transform Your Digital Experience",
    subtitle:
      "Unleash the power of cutting-edge technology to revolutionize your business.",
    content:
      "Join thousands of forward-thinking companies who've already made the leap to next-generation solutions. Our platform combines innovation with reliability to deliver results that exceed expectations.\n\n✨ Boost productivity by 300%\n🚀 Launch in under 24 hours\n💡 AI-powered insights included\n🔒 Enterprise-grade security\n\nDon't just adapt to the future—create it. Your journey to digital transformation starts here.",
    buttonText: "Start Free Trial",
    gradient: "bg-gradient-to-r from-blue-500 to-teal-400",
    titleStyle:
      "text-6xl font-bold font-sans text-white tracking-tight leading-tight",
    subtitleStyle: "text-2xl font-light font-serif text-white/90 mt-4",
    image: "/Screenshot from 2025-09-17 14-23-40.png",
    height: "min-h-[700px]", 
  },
  {
    id: 2,
    name: "Features Section",
    title: "Features Overview",
    subtitle: "Highlight the key features of your product or service.",
    content: "• Fast performance\n• Easy integration\n• Customizable options",
    gradient: "bg-gradient-to-br from-blue-600 to-navy-600",
    titleStyle: "text-5xl font-semibold font-mono text-white uppercase",
    subtitleStyle: "text-lg font-normal font-sans text-white mt-2",
    height: "min-h-[450px]", 
  },
  {
    id: 5,
    name: "Testimonials Section",
    title: "Testimonials",
    subtitle: "Share what your customers are saying.",
    content:
      "This product transformed our business. Highly recommended! — Sarah J.",
    gradient: "bg-gradient-to-br from-indigo-500 to-indigo-700",
    titleStyle: "text-4xl font-serif text-white italic",
    subtitleStyle: "text-md font-light font-sans text-gray-100 mt-3",
    height: "min-h-[350px]", 
  },
  {
    id: 7,
    name: "Pricing Section",
    title: "Pricing Plans",
    subtitle: "Display your pricing tiers with clarity.",
    content: "Basic - $10/mo\nPro - $25/mo\nEnterprise - $50/mo",
    buttonText: "Choose Plan",
    gradient: "bg-gradient-to-r from-blue-500 to-navy-500",
    titleStyle: "text-4xl font-extrabold font-cursive text-white uppercase",
    subtitleStyle: "text-lg font-normal font-mono text-white mt-2",
    height: "min-h-[400px]", 
  },
  {
    id: 9,
    name: "Contact Section",
    title: "Contact Form",
    subtitle: "Let users get in touch with you easily.",
    content: "Name: \nEmail: \nMessage:",
    buttonText: "Send Message",
    gradient: "bg-gradient-to-r from-blue-300 to-teal-400",
    titleStyle: "text-4xl font-medium font-sans text-navy-900",
    subtitleStyle: "text-xl font-semibold font-serif text-gray-700 mt-3",
    image: "/yT9z1wa-technology-wallpaper.jpg",
    height: "min-h-[500px]", 
  },
  {
    id: 10,
    name: "About Us Section",
    title: "Our Story",
    subtitle: "Discover the journey behind our creation.",
    content: `In the beginning, there was an idea. An idea born from passion...`,
    gradient: "bg-gradient-to-r from-pink-500 to-orange-400",
    titleStyle: "text-4xl font-serif font-bold text-white",
    subtitleStyle: "text-lg font-normal font-sans text-gray-200 mt-3",
    image: "/UkpUlVc-technology-wallpaper.jpg",
    height: "min-h-[550px]", 
  },
  {
    id: 11,
    name: "Services Section",
    title: "Our Premium Services",
    subtitle: "Comprehensive solutions tailored to your business needs.",
    content:
      "🎯 Strategic Consulting\nGet expert guidance to align technology with your business goals\n\n💻 Custom Development\nBespoke software solutions built for your unique requirements\n\n🔧 Technical Support\n24/7 dedicated support from our experienced team\n\n📊 Analytics & Insights\nData-driven decisions with comprehensive reporting tools",
    buttonText: "View All Services",
    gradient: "bg-gradient-to-br from-purple-600 to-blue-800",
    titleStyle: "text-5xl font-bold font-sans text-white",
    subtitleStyle: "text-xl font-light font-serif text-white/90 mt-3",
    height: "min-h-[500px]",
  },
  {
    id: 12,
    name: "Team Section",
    title: "Meet Our Expert Team",
    subtitle: "Passionate professionals dedicated to your success.",
    content:
      "👥 50+ Industry Experts\nCertified professionals with years of experience\n\n🌍 Global Presence\nServing clients across 40+ countries worldwide\n\n🏆 Award-Winning Team\nRecognized leaders in innovation and customer satisfaction\n\n🎓 Continuous Learning\nStaying ahead with latest technologies and trends\n\nOur diverse team brings together the best minds from technology, design, and business strategy.",
    buttonText: "Meet the Team",
    gradient: "bg-gradient-to-r from-green-500 to-emerald-600",
    titleStyle: "text-4xl font-extrabold font-sans text-white",
    subtitleStyle: "text-lg font-medium font-serif text-white/90 mt-2",
    image: "/wp15803223-8k-ultra-hd-wallpapers.jpg",
    height: "min-h-[450px]",
  },
  {
    id: 13,
    name: "Statistics Section",
    title: "Success by the Numbers",
    subtitle: "Real results that speak for themselves.",
    content:
      "📈 500K+ Active Users\nTrusted by half a million professionals worldwide\n\n⚡ 99.9% Uptime\nReliable performance you can count on\n\n💰 $2.5B+ Revenue Generated\nHelping our clients achieve remarkable growth\n\n🌟 4.9/5 Customer Rating\nExceptional satisfaction across all platforms\n\n🚀 10X Faster Processing\nCutting-edge technology for superior performance",
    gradient: "bg-gradient-to-br from-orange-500 to-red-600",
    titleStyle: "text-5xl font-black font-mono text-white uppercase",
    subtitleStyle: "text-xl font-normal font-sans text-white/95 mt-3",
    height: "min-h-[480px]",
  },
  {
    id: 14,
    name: "Integration Section",
    title: "Seamless Integrations",
    subtitle: "Connect with your favorite tools and platforms effortlessly.",
    content:
      "🔗 200+ Native Integrations\nPopular tools like Slack, Salesforce, Google Workspace, and more\n\n⚙️ Custom API Solutions\nFlexible APIs for unique integration requirements\n\n🔄 Real-time Sync\nInstant data synchronization across all platforms\n\n🛡️ Secure Connections\nEnterprise-grade security for all integrations\n\nTransform your workflow with powerful connections that just work.",
    buttonText: "Browse Integrations",
    gradient: "bg-gradient-to-r from-cyan-500 to-blue-600",
    titleStyle: "text-4xl font-bold font-sans text-white",
    subtitleStyle: "text-lg font-light font-serif text-white/90 mt-2",
    image:
      "/wp15795920-silver-surfer-desktop-4k-wallpapers.jpg",
    height: "min-h-[420px]",
  },
  {
    id: 15,
    name: "Resources Section",
    title: "Knowledge Hub",
    subtitle: "Everything you need to succeed with our platform.",
    content:
      "📚 Comprehensive Documentation\nStep-by-step guides and API references\n\n🎥 Video Tutorials\nLearn at your own pace with our expert-led courses\n\n📖 Case Studies\nReal-world examples of successful implementations\n\n🔍 Best Practices\nProven strategies from industry leaders\n\n💬 Community Forum\nConnect with other users and share insights\n\nEmpowering you with knowledge for maximum success.",
    buttonText: "Explore Resources",
    gradient: "bg-gradient-to-br from-violet-600 to-purple-700",
    titleStyle: "text-4xl font-semibold font-sans text-white",
    subtitleStyle: "text-xl font-medium font-serif text-white/90 mt-3",
    height: "min-h-[460px]",
  },
  {
    id: 16,
    name: "CTA Section",
    title: "Ready to Get Started?",
    subtitle: "Join thousands of satisfied customers today.",
    content:
      "🎉 Special Launch Offer\n50% off your first year - Limited time only!\n\n✅ No Setup Fees\nGet started immediately with zero upfront costs\n\n🔒 30-Day Money-Back Guarantee\nTry risk-free with our satisfaction promise\n\n📞 Free Consultation\nPersonalized onboarding with our experts\n\nDon't wait - transform your business today and join the success stories of tomorrow!",
    buttonText: "Start Your Journey",
    gradient: "bg-gradient-to-r from-rose-500 to-pink-600",
    titleStyle: "text-5xl font-extrabold font-sans text-white text-center",
    subtitleStyle:
      "text-2xl font-light font-serif text-white/95 mt-4 text-center",
    height: "min-h-[100px]",
  },
];

export default DummyWidgets;